### ISSUE TITLE
`mix burn` cannot be operated from Docker container

### ISSUE THREAD

**Issue by takasehideki** [NervesJP/nerves-devcontainer#5]
It is nature that burning firmware to microSD from Docker container is hard to support.
But it become awesome if `mix burn` can be operated from docker dev-container.

**Comment by takasehideki** [comment]
Status on macOS

```
root@be6d80382017:/workspaces/nerves-devcontainer/test# mix burn 
==> nerves
==> test

Nerves environment
  MIX_TARGET:   rpi4
  MIX_ENV:      dev

** (Mix) Could not auto detect your SD card
```

This is because Docker container cannot access/detect microSD on host PC. One possible solution is calling `fwup` on host PC from Docker container. Alternatively, binding microSD device to docker container filesystem. But, are they possible?

**Comment by takasehideki** [comment]
status on windows:

```
root@923930b7aad1:/workspaces/nerves-devcontainer/test# mix burn 
==> nerves
==> test

Nerves environment
  MIX_TARGET:   rpi4
  MIX_ENV:      dev

** (ErlangError) Erlang error: :enoent
    (nerves 1.7.0) lib/nerves/port.ex:88: Nerves.Port.validate("cmd.exe", ["/c", "echo %TEMP%"], [])
    (nerves 1.7.0) lib/nerves/port.ex:25: Nerves.Port.do_cmd/4
    (nerves 1.7.0) lib/nerves/utils/wsl.ex:94: Nerves.Utils.WSL.get_temp_file_location/1
    (nerves 1.7.0) lib/nerves/utils/wsl.ex:237: Nerves.Utils.WSL.make_file_accessible/3
    (nerves 1.7.0) lib/mix/tasks/burn.ex:66: Mix.Tasks.Burn.run/1
    (mix 1.11.2) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.2) lib/mix/cli.ex:84: Mix.CLI.run_task/2
```

This is because current Nerves supports (native) WSL2 environment for Windows users. We may modify Nerves environment to resolve this situation.
The way to detect whether a container is based on WSL2 or native docker is `uname -r` and `ls /.dockerenv`
Ref: https://github.com/ETrobocon/etrobo/blob/master/scripts/etroboenv.sh#L55

**Comment by takasehideki** [comment]
This issue was transferred to more precise repository.
https://github.com/NervesJP/docker-nerves/issues/1
